In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

import plotly.express as px

In [2]:
data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}

df = pd.DataFrame(data)

df.to_csv("student_performance.csv", index=False)

df

    Study_Hours  Attendance  Assignments  Marks
0             1          60            2     35
1             2          65            3     40
2             3          70            4     45
3             4          72            5     50
4             5          75            5     58
5             6          80            6     65
6             7          82            7     72
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

### Part 1 — Dataset Exploration

In [3]:
df = pd.read_csv("student_performance.csv")

print("First 5 Rows")
print(df.head())

print("\nLast 5 Rows")
print(df.tail())

print("\nShape")
print(df.shape)

print("\nColumns")
print(df.columns)

print("\nData Types")
print(df.dtypes)

print("\nSummary Statistics")
print(df.describe())

First 5 Rows
   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

Last 5 Rows
    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

Shape
(12, 4)

Columns
Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

Data Types
Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

Summary Statistics
       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

### Part 2 — Identify Features and Label

In [4]:
X = df[["Study_Hours","Attendance","Assignments"]]

y = df["Marks"]

print("Features")
print(X)

print("\nLabel")
print(y)

Features
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

### Part 4 — Train-Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (9, 3)
X_test shape: (3, 3)
y_train shape: (9,)
y_test shape: (3,)

### Part 5 — Train Your First Mode

In [6]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Coefficients:")
print(model.coef_)

print("\nIntercept:")
print(model.intercept_)

Coefficients:
[ 3.45487968  1.34491979 -2.40274064]

Intercept:
-48.100601604278054

### Part 6 — Predictions

In [7]:
new_data = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10]
})

predictions = model.predict(new_data)

prediction_df = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10],
    "Predicted_Marks":predictions
})

prediction_df

   Study_Hours  Attendance  Assignments  Predicted_Marks
0            5          80            5        64.753676
1            8          90            8        81.359291
2           12          95           10        97.097928

### Part 7 — Actual vs Predicted Comparison

In [8]:
y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Marks":y_test.values,
    "Predicted Marks":y_pred
})

comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

comparison

   Actual Marks  Predicted Marks  Difference
0            92        92.011029    0.011029
1            88        88.269051    0.269051
2            35        31.243984    3.756016

In [9]:
highest_error = comparison.loc[
    comparison["Difference"].idxmax()
]

print(highest_error)

Actual Marks       35.000000
Predicted Marks    31.243984
Difference          3.756016
Name: 2, dtype: float64

### Part 8 — Model Evaluation

In [10]:
mae = mean_absolute_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("MAE =", mae)

print("R2 Score =", r2)

MAE = 1.3453654188948245
R2 Score = 0.9929962957709836

### Part 9 — Data Visualization Challenge

#### Plot 1

In [11]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

#### Plot 2

In [12]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    hover_data=["Study_Hours","Assignments"],
    title="Attendance vs Marks"
)

fig.show()

#### Plot 3

In [13]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Assignments",
    title="Assignments vs Marks"
)

fig.show()

#### Plot 4

In [14]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    trendline="ols",
    title="Regression Line Visualization"
)

fig.show()

#### Plot 5

In [15]:
future_data = pd.DataFrame({
    "Study_Hours":range(1,16),
    "Attendance":[80]*15,
    "Assignments":[6]*15
})

future_predictions = model.predict(future_data)

future_df = pd.DataFrame({
    "Study_Hours":range(1,16),
    "Predicted_Marks":future_predictions
})

fig = px.line(
    future_df,
    x="Study_Hours",
    y="Predicted_Marks",
    title="Predicted Marks Trend"
)

fig.show()